FROM python:3.11-slim

WORKDIR /proj_data/zst

COPY backend.py .

RUN pip install --no-cache-dir fastapi uvicorn[standard]

EXPOSE 6060

CMD ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "6060"]
